// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmIKLbUuqelTkOlupZchOY1nXBSSWF7fs',
    appId: '1:934012847497:web:d60302d6c0805e15974d58',
    messagingSenderId: '934012847497',
    projectId: 'microblog-app-001',
    authDomain: 'microblog-app-001.firebaseapp.com',
    storageBucket: 'microblog-app-001.firebasestorage.app',
    measurementId: 'G-P3S5RY0DBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCAEQzY9hzjcRv1K9ixg9a4giNoisJSvo',
    appId: '1:934012847497:android:58fc977d06bb195e974d58',
    messagingSenderId: '934012847497',
    projectId: 'microblog-app-001',
    storageBucket: 'microblog-app-001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc9IoGicRE0i6Sk7pM3VpSUPbdesft0fs',
    appId: '1:934012847497:ios:5837802ddf1af5a6974d58',
    messagingSenderId: '934012847497',
    projectId: 'microblog-app-001',
    storageBucket: 'microblog-app-001.firebasestorage.app',
    iosClientId: '934012847497-3fp6s4dnbmpnq4qpptrdslf06dvgdtve.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc9IoGicRE0i6Sk7pM3VpSUPbdesft0fs',
    appId: '1:934012847497:ios:5837802ddf1af5a6974d58',
    messagingSenderId: '934012847497',
    projectId: 'microblog-app-001',
    storageBucket: 'microblog-app-001.firebasestorage.app',
    iosClientId: '934012847497-3fp6s4dnbmpnq4qpptrdslf06dvgdtve.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );
}
